import { defineConfig, type Plugin } from 'vite';

function jarvisBrowserBridge(): Plugin {
  return {
    name: 'jarvis-browser-bridge',
    transform(code, id) {
      if (id.endsWith('/src/styles.css')) {
        return { code: code + `
.browser-shell{border:1px solid var(--line);background:#040b10;border-radius:12px;overflow:hidden;box-shadow:0 25px 70px #0008;min-height:620px;display:grid;grid-template-rows:auto auto auto 1fr auto}.browser-toolbar{display:grid;grid-template-columns:auto auto auto 1fr auto;gap:7px;padding:10px;border-bottom:1px solid var(--line);background:#07151c}.browser-toolbar button:not(.primary){border:1px solid #21414c;background:#08151c;color:#9bc5cf;border-radius:6px;padding:8px 11px;cursor:pointer}.browser-toolbar input{background:#02070a;border:1px solid #21414c;color:#dffaff;border-radius:7px;padding:10px 13px;outline:0}.browser-toolbar input:focus{border-color:var(--cyan);box-shadow:0 0 20px #55d6ff14}.browser-tabs{display:flex;align-items:center;gap:8px;padding:7px 10px;background:#061017;border-bottom:1px solid var(--line)}.browser-tab{border:1px solid #21414c;background:#0a1b23;color:#c9f5ff;border-radius:6px;padding:7px 12px;font-size:9px;cursor:pointer}.browser-engine{margin-left:auto;color:#58737d;font-size:7px;letter-spacing:.15em}.browser-status{padding:6px 12px;color:#52717b;font-size:7px;letter-spacing:.14em;border-bottom:1px solid var(--line);background:#02070a}.browser-shell iframe{width:100%;height:100%;min-height:500px;border:0;background:#fff}.browser-fallback{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:8px 12px;background:#061017;color:#58737d;font-size:8px;border-top:1px solid var(--line)}.browser-fallback button{border:1px solid #21414c;background:#08151c;color:var(--cyan);border-radius:5px;padding:6px 9px;font-size:7px;cursor:pointer}@media(max-width:760px){.browser-toolbar{grid-template-columns:auto auto auto 1fr}.browser-toolbar .primary{grid-column:1/-1}.browser-shell{min-height:540px}.browser-shell iframe{min-height:420px}}`, map: null };
      }
      if (!id.endsWith('/src/main.ts')) return null;
      let out = code;
      out = out.replace(/function openExternal\(url:string,title:string\)\{[\s\S]*?\}\nfunction searchUrl/, `function openExternal(url:string,title:string){try{const u=new URL(url,location.href);if(!/^https?:$/.test(u.protocol))return;void pushRecentTab(title,u.toString());recent.unshift({title,url:u.toString(),time:Date.now()});recent=recent.filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i).slice(0,12);if(active!=='web'){active='web';render();setTimeout(()=>loadBrowserUrl(u.toString(),title),0)}else loadBrowserUrl(u.toString(),title)}catch{}}
function loadBrowserUrl(url:string,title='Web page'){const frame=document.querySelector<HTMLIFrameElement>('#browserFrame');const address=document.querySelector<HTMLInputElement>('#browserAddress');const status=document.querySelector<HTMLElement>('#browserStatus');if(address)address.value=url;if(status)status.textContent='LOADING // '+title.toUpperCase();if(frame){frame.src=url;frame.onload=()=>{if(status)status.textContent='PAGE READY // EMBEDDED WEBVIEW'};frame.onerror=()=>{if(status)status.textContent='EMBED BLOCKED // USE SYSTEM BROWSER'}}}
function searchUrl`);
      out = out.replace(/function web\(\)\{[\s\S]*?\}\nfunction maps/, `function web(){return \`<div class="apphead"><div><p class="eyebrow">INTERNET / BROWSER</p><h2>JARVIS Browser</h2><p class="sub">A browser workspace inside the JARVIS shell. Navigation, search and media stay inside the command center.</p></div></div><div class="browser-shell"><div class="browser-toolbar"><button id="browserBack" title="Back">‹</button><button id="browserForward" title="Forward">›</button><button id="browserReload" title="Reload">↻</button><input id="browserAddress" value="https://search.brave.com" placeholder="Search or enter address"><button class="primary" id="browserGo">GO</button></div><div class="browser-tabs"><button class="browser-tab active">＋ New tab</button><span class="browser-engine">SEARCH: \${searchEngine.toUpperCase()}</span></div><div id="browserStatus" class="browser-status">READY // JARVIS EMBEDDED WEBVIEW</div><iframe id="browserFrame" title="JARVIS Browser" src="https://search.brave.com" loading="eager" referrerpolicy="no-referrer" allow="fullscreen; autoplay; picture-in-picture"></iframe><div class="browser-fallback"><span>Some sites refuse iframe embedding by design. JARVIS keeps the fallback explicit.</span><button id="browserSystemOpen">OPEN IN SYSTEM BROWSER</button></div></div>\`}
function maps`);
      out = out.replace(/function setupWeb\(\)\{[\s\S]*?\}\nfunction setupMaps/, `function setupWeb(){const address=()=> (document.querySelector('#browserAddress') as HTMLInputElement).value.trim();const go=()=>{let u=address();if(!u)return;if(!/^https?:\\/\\//i.test(u))u=searchUrl(u);loadBrowserUrl(u,'Address navigation')};document.querySelector('#browserGo')?.addEventListener('click',go);document.querySelector('#browserAddress')?.addEventListener('keydown',e=>{if(e.key==='Enter')go()});document.querySelector('#browserReload')?.addEventListener('click',()=>{const f=document.querySelector<HTMLIFrameElement>('#browserFrame');if(f)f.src=f.src});document.querySelector('#browserBack')?.addEventListener('click',()=>{try{document.querySelector<HTMLIFrameElement>('#browserFrame')?.contentWindow?.history.back()}catch{}});document.querySelector('#browserForward')?.addEventListener('click',()=>{try{document.querySelector<HTMLIFrameElement>('#browserFrame')?.contentWindow?.history.forward()}catch{}});document.querySelector('#browserSystemOpen')?.addEventListener('click',()=>{const u=address();if(/^https?:\\/\\//i.test(u))window.open(u,'_blank','noopener,noreferrer')});document.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach(b=>b.onclick=()=>{const q=address();loadBrowserUrl(searchUrl(q,b.dataset.provider!),b.dataset.provider!+' search')})}
function setupMaps`);
      return { code: out, map: null };
    }
  };
}

export default defineConfig({ base: './', plugins: [jarvisBrowserBridge()] });
