import { AppId, addNote, getSetting, notes, setSetting } from './db';
import './styles.css';
const apps:Record<AppId,{name:string;icon:string}>={home:{name:'Desktop',icon:'⌂'},calculator:{name:'Calculator',icon:'＋'},snake:{name:'Snake',icon:'◈'},files:{name:'Files',icon:'▣'},notes:{name:'Notes',icon:'✎'},settings:{name:'Settings',icon:'⚙'}};
let active:AppId='home'; let theme=await getSetting<'dark'|'light'>('theme','dark');
const app=document.querySelector<HTMLDivElement>('#app')!;
function shell(content:string){app.innerHTML=`<div class="os ${theme}"><header><div class="brand"><span class="orb">✦</span><span>JARVIS</span></div><div class="status"><span id="clock"></span><button id="themeBtn" aria-label="Toggle theme">◐</button></div></header><main><aside>${Object.entries(apps).map(([id,a])=>`<button class="nav ${id===active?'selected':''}" data-app="${id}" title="${a.name}"><b>${a.icon}</b><span>${a.name}</span></button>`).join('')}</aside><section class="workspace">${content}</section></main><footer><span>JARVIS OS • Local-first runtime</span><span>READY</span></footer></div>`;bind();tick()}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-app]').forEach(b=>b.onclick=()=>{active=b.dataset.app as AppId;render()});document.querySelector<HTMLButtonElement>('#themeBtn')!.onclick=async()=>{theme=theme==='dark'?'light':'dark';await setSetting('theme',theme);render()}}
function tick(){const el=document.querySelector('#clock');if(el){el.textContent=new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());setTimeout(tick,1000)}}
function render(){const c=active==='home'?home():active==='calculator'?calculator():active==='snake'?snake():active==='files'?files():active==='notes'?notesApp():settings();shell(c);setTimeout(afterRender,0)}
function home(){return `<div class="hero"><div><p class="eyebrow">JARVIS OS / ONLINE</p><h1>Good afternoon.</h1><p class="sub">A lightweight personal desktop that lives in your browser.</p><div class="chips"><span>Local-first</span><span>Fast boot</span><span>Offline-ready</span></div></div><div class="pulse">✦</div></div><div class="grid">${(['calculator','snake','files','notes','settings'] as AppId[]).map(id=>`<button class="card" data-app="${id}"><span class="bigicon">${apps[id].icon}</span><strong>${apps[id].name}</strong><small>Open app</small></button>`).join('')}</div>`}
function calculator(){return `<div class="apphead"><div><p class="eyebrow">UTILITY</p><h2>Calculator</h2></div></div><div class="calc"><input id="display" value="0" readonly><div class="keys">${['C','⌫','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','±','0','.','='].map(x=>`<button data-key="${x}" class="${x==='='?'equals':''}">${x}</button>`).join('')}</div></div>`}
function snake(){return `<div class="apphead"><div><p class="eyebrow">ARCADE</p><h2>Snake</h2><p class="sub">Arrow keys or WASD. Eat the pulse. Don't eat yourself.</p></div><button class="primary" id="snakeStart">Start</button></div><canvas id="snakeCanvas" width="420" height="420"></canvas><div class="score" id="score">Score 0</div>`}
function files(){return `<div class="apphead"><div><p class="eyebrow">SYSTEM</p><h2>Files</h2><p class="sub">Browser sandbox storage. Your files never leave this runtime.</p></div></div><div class="filebox"><div>▣ <strong>Jarvis Workspace</strong></div><div class="file">⌁ <span>Local database</span><small>IndexedDB</small></div><div class="file">◈ <span>App registry</span><small>Built-in</small></div><div class="file">⚙ <span>Preferences</span><small>Persistent</small></div></div>`}
function notesApp(){return `<div class="apphead"><div><p class="eyebrow">PERSONAL</p><h2>Notes</h2></div></div><div class="note-compose"><textarea id="note" placeholder="Write something…"></textarea><button class="primary" id="saveNote">Save note</button></div><div class="notes" id="notesList"><div class="empty">Loading notes…</div></div>`}
function escapeHtml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]!))}
function settings(){return `<div class="apphead"><div><p class="eyebrow">SYSTEM</p><h2>Settings</h2></div></div><div class="settings"><div><strong>Appearance</strong><span>Switch between dark and light desktop</span></div><button class="primary" id="settingsTheme">${theme==='dark'?'Light mode':'Dark mode'}</button></div><div class="settings"><div><strong>Runtime</strong><span>Native browser APIs • IndexedDB • no server required</span></div><span class="badge">LOCAL</span></div>`}
async function afterRender(){
 document.querySelector<HTMLButtonElement>('#settingsTheme')?.addEventListener('click',async()=>{theme=theme==='dark'?'light':'dark';await setSetting('theme',theme);render()});
 document.querySelector<HTMLButtonElement>('#saveNote')?.addEventListener('click',async()=>{const t=(document.querySelector('#note') as HTMLTextAreaElement).value.trim();if(t){await addNote(t);render()}});
 if(active==='notes'){const list=document.querySelector('#notesList')!;const ns=await notes();list.innerHTML=ns.slice().reverse().map(n=>`<article><p>${escapeHtml(n.text)}</p><small>${new Date(n.created).toLocaleString()}</small></article>`).join('')||'<div class="empty">No notes yet.</div>'}
 if(active==='calculator')setupCalc(); if(active==='snake')setupSnake();
}
function setupCalc(){let expr='';const d=document.querySelector<HTMLInputElement>('#display')!;document.querySelectorAll<HTMLButtonElement>('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key!;if(k==='C'){expr='';d.value='0';return}if(k==='⌫'){expr=expr.slice(0,-1);d.value=expr||'0';return}if(k==='='){try{const safe=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/[^0-9+\-*/%.() ]/g,'');const result=Function(`"use strict";return (${safe})`)();expr=String(result);d.value=expr}catch{d.value='Error';expr=''}return}if(k==='±'){expr=expr.startsWith('-')?expr.slice(1):'-'+expr;d.value=expr;return}expr+=k;d.value=expr})}
function setupSnake(){const c=document.querySelector<HTMLCanvasElement>('#snakeCanvas')!,ctx=c.getContext('2d')!,scoreEl=document.querySelector('#score')!;let snake:[number,number][]=[[10,10]],food:[number,number]=[15,10],dir:[number,number]=[1,0],score=0,running=false,timer:number;const reset=()=>{snake=[[10,10]];food=[15,10];dir=[1,0];score=0;scoreEl.textContent='Score 0'};const draw=()=>{ctx.clearRect(0,0,420,420);ctx.fillStyle='#0a0d13';ctx.fillRect(0,0,420,420);ctx.fillStyle='#7dd3fc';ctx.fillRect(food[0]*20+3,food[1]*20+3,14,14);ctx.fillStyle='#f5f5f5';snake.forEach(([x,y])=>ctx.fillRect(x*20+2,y*20+2,16,16))};const step=()=>{const h:[number,number]=[snake[0][0]+dir[0],snake[0][1]+dir[1]];if(h[0]<0||h[0]>=21||h[1]<0||h[1]>=21||snake.some(([x,y])=>x===h[0]&&y===h[1])){running=false;clearInterval(timer);return}snake.unshift(h);if(h[0]===food[0]&&h[1]===food[1]){score++;scoreEl.textContent=`Score ${score}`;food=[Math.floor(Math.random()*21),Math.floor(Math.random()*21)]}else snake.pop();draw()};document.addEventListener('keydown',e=>{const m:Record<string,[number,number]>={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const n=m[e.key];if(n&&!(n[0]===-dir[0]&&n[1]===-dir[1]))dir=n});document.querySelector('#snakeStart')!.addEventListener('click',()=>{if(running)return;reset();running=true;draw();timer=window.setInterval(step,120)});draw()}
render();
