import { AppId } from './db';
import { getTelemetry, runCommand, speak, startVoice, type Telemetry, type VoiceConfig } from './jarvis';
import './styles.css';

type AppMeta={name:string;icon:string;group:string};
const apps:Record<AppId,AppMeta>={home:{name:'Command',icon:'◉',group:'CORE'},calculator:{name:'Calc',icon:'+',group:'TOOLS'},snake:{name:'Games',icon:'◇',group:'TOOLS'},files:{name:'Files',icon:'□',group:'WORKSPACE'},notes:{name:'Notes',icon:'✎',group:'WORKSPACE'},settings:{name:'Settings',icon:'⚙',group:'SYSTEM'},api:{name:'API Lab',icon:'⇄',group:'ENGINEERING'},remote:{name:'SFTP',icon:'↔',group:'ENGINEERING'},web:{name:'Search',icon:'⌕',group:'INTELLIGENCE'},maps:{name:'Maps',icon:'⌖',group:'INTELLIGENCE'},media:{name:'Media',icon:'▶',group:'INTELLIGENCE'}};
let active:AppId='home',theme:'dark'|'light'='dark',voiceCfg:VoiceConfig={voiceName:'',rate:.92,pitch:.54,volume:.96,language:'en-GB'},telemetry:Telemetry={online:navigator.onLine,battery:null,charging:null,memory:null,cores:navigator.hardwareConcurrency??null,network:'online'},clockTimer:number|undefined;
let newsAbort:AbortController|null=null;let newsCache=new Map<string,string>();let newsBooted=false;
const root=document.querySelector<HTMLDivElement>('#app');
const clockFormatter=new Intl.DateTimeFormat([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const esc=(s:string)=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]!));
const loadFeature=(name:string)=>{const fn=(window as Window&{jarvisLoadFeature?: (feature:string)=>Promise<void>}).jarvisLoadFeature;return typeof fn==='function'?fn(name):Promise.resolve()};
function pageHead(k:string,t:string,s:string){return `<div class="page-head"><div><p class="eyebrow">${k}</p><h1>${t}</h1><p class="sub">${s}</p></div></div>`}
function newsDesk(){return `<section class="panel" id="newsDesk"><div class="panel-head"><span>INTELLIGENCE / LIVE NEWS</span><span class="live" id="newsStatus">READY</span></div><div class="search-row"><select id="newsGenre"><option value="WORLD">WORLD</option><option value="INDIA">INDIA</option><option value="AI">AI</option><option value="TECH">TECH</option></select><button class="primary" id="refreshNews">REFRESH</button></div><div id="newsCards"><div class="empty">Loading live intelligence…</div></div></section>`}
function home(){const homeIds:AppId[]=['web','calculator','snake','files','notes','settings'];return `${pageHead('CORE / COMMAND','Command Center','Ask JARVIS to search, calculate, navigate or play.')}<section class="command-surface"><form id="commandForm"><span class="prompt">›</span><input id="commandInput" autocomplete="off" placeholder="Ask JARVIS…"><button type="button" class="voice" id="voiceBtn">◉</button><button type="submit" class="execute">RUN</button></form><div id="jarvisReply" class="jarvis-reply"></div></section>${newsDesk()}<section class="panel"><div class="panel-head"><span>CORE MODULES</span><span class="live">READY</span></div><div class="module-grid">${homeIds.map(id=>{const a=apps[id];return `<button class="module-card" data-app="${id}"><span class="module-icon">${a.icon}</span><div><small>${a.group}</small><strong>${a.name}</strong><p>Open ${a.name}</p></div><b>›</b></button>`}).join('')}</div></section>`}
function web(){return `${pageHead('INTELLIGENCE / WEB','Search Hub','Live web search inside JARVIS.')}<div class="search-panel"><div class="search-row"><select id="webProvider"><option value="brave">Brave</option><option value="bing">Bing</option></select><input id="webQuery" placeholder="Search the web…"><button class="primary" id="webSearch">SEARCH</button></div><div id="jwsStatus"></div><div id="jwsResults"></div></div>`}
function maps(){return `${pageHead('INTELLIGENCE / MAPS','Maps','Search destinations and inspect the result in-shell.')}<div class="maps-grid"><section class="panel"><div class="search-row"><input id="mapQuery" placeholder="Search a place…"><button class="primary" id="mapSearch">SEARCH</button></div><div id="mapResults"><div class="empty">Search for a place to begin.</div></div></section><section class="panel map-frame" id="mapFrame"><div class="empty">Search for a place to begin.</div></section></div>`}
function media(){return `${pageHead('INTELLIGENCE / MEDIA','Media','Search YouTube or paste a URL.')}<div class="media-workspace"><section class="media-main panel"><div class="search-row"><input id="videoQuery" placeholder="Search YouTube or paste a URL…"><button class="primary" id="videoSearch">SEARCH</button></div><div id="mediaState">READY</div><div id="jarvisPlayer" class="jarvis-player-frame"><div class="player-empty"><span>▶</span><strong>SELECT A VIDEO</strong><small>Choose a result or paste a YouTube URL.</small></div></div></section><aside class="media-side panel"><div id="videoResults" class="video-results"><div class="empty">No results yet.</div></div></aside></div>`}
function settings(){return `${pageHead('SYSTEM / CONFIGURATION','Settings','Core configuration.')}<section class="settings-grid"><div class="settings-card"><h3>Appearance</h3><button class="primary" id="settingsTheme">${theme==='dark'?'LIGHT MODE':'DARK MODE'}</button></div><div class="settings-card"><h3>Voice</h3><button class="secondary" id="testVoice">TEST VOICE</button></div></section>`}
function calculator(){return `${pageHead('TOOLS / CALCULATOR','Calculator','Local arithmetic console.')}<div class="calc"><input id="calcDisplay" aria-label="Calculator display" value="0"><div class="keys">${['7','8','9','/','4','5','6','*','1','2','3','-','0','.','=','+'].map(x=>`<button type="button" data-key="${x}" class="${x==='='?'equals':''}">${x}</button>`).join('')}</div></div>`}
function simpleModule(title:string,sub:string,label:string){return `${pageHead('JARVIS WORKSPACE',title,sub)}<section class="panel info-card"><p class="eyebrow">LOCAL-FIRST</p><h3>${label}</h3><p>This module is available from the stable core shell.</p></section>`}
function shell(content:string){if(!root)return;const existing=root.querySelector<HTMLElement>('.os');if(!existing){root.innerHTML=`<div class="os ${theme}"><header class="topbar"><div class="brand" data-app="home"><span class="brand-orb"><span>J</span></span><div><strong>J.A.R.V.I.S</strong><small>PERSONAL INTELLIGENCE SYSTEM</small></div></div><div class="top-center"><span class="system-state"><i></i> CORE NOMINAL</span><span class="clock" id="clock"></span></div></header><main class="os-main"><aside class="rail"><div class="nav-group">${Object.entries(apps).map(([id,a])=>`<button type="button" class="nav ${id===active?'selected':''}" data-app="${id}"><b>${a.icon}</b><span>${a.name}</span></button>`).join('')}</div></aside><section class="workspace" id="workspace"></section></main><footer class="statusbar"><span>JARVIS CORE <i></i> LOCAL-FIRST</span><span id="networkState">${telemetry.online?'NETWORK NOMINAL':'OFFLINE / DEGRADED'}</span></footer></div>`;bindNavigation();}const os=root.querySelector<HTMLElement>('.os');os?.classList.toggle('dark',theme==='dark');os?.classList.toggle('light',theme==='light');const workspace=root.querySelector<HTMLElement>('#workspace');if(workspace)workspace.innerHTML=content;const network=root.querySelector('#networkState');if(network)network.textContent=telemetry.online?'NETWORK NOMINAL':'OFFLINE / DEGRADED';updateClock();bindNavigation();}
function bindNavigation(){root?.querySelectorAll<HTMLElement>('[data-app]').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';el.addEventListener('click',()=>{const id=el.getAttribute('data-app') as AppId;if(id){active=id;render()}})})}
function markSelected(){root?.querySelectorAll<HTMLElement>('.nav[data-app]').forEach(el=>el.classList.toggle('selected',el.dataset.app===active))}
function updateClock(){const el=document.querySelector('#clock');if(!el)return;el.textContent=clockFormatter.format(new Date());if(clockTimer===undefined)clockTimer=window.setInterval(updateClock,1000)}
function render(){if(!root)return;const content=active==='home'?home():active==='web'?web():active==='maps'?maps():active==='media'?media():active==='settings'?settings():active==='calculator'?calculator():active==='snake'?simpleModule('Games','Arcade workspace','Game console'):active==='files'?simpleModule('Files','Local workspace','File system'):active==='notes'?simpleModule('Notes','Persistent notes','Notes console'):active==='api'?simpleModule('API Lab','REST engineering workspace','Request client'):simpleModule('SFTP','Secure transfer workspace','Remote transfer');shell(content);markSelected();requestAnimationFrame(afterRender)}
async function prepareFeature(){try{if(window.matchMedia?.('(max-width: 760px)').matches)await loadFeature('mobile');if(active==='web')await loadFeature('web');else if(active==='media')await loadFeature('media');else if(active==='api'||active==='remote')await loadFeature('engineering');else if(active==='notes')await loadFeature('notes');else if(active==='snake')await loadFeature('games')}catch(error){console.warn('JARVIS feature load failed',error)}}
async function speakJarvis(text:string){try{await loadFeature('voice')}catch{}speak(text,voiceCfg)}
function afterRender(){void prepareFeature();markSelected();document.querySelector('#settingsTheme')?.addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';render()});document.querySelector('#testVoice')?.addEventListener('click',async()=>{await loadFeature('voice').catch(()=>{});speak('JARVIS core is online.',voiceCfg)});document.querySelector('#commandForm')?.addEventListener('submit',e=>{e.preventDefault();void executeCommand()});document.querySelector('#voiceBtn')?.addEventListener('click',async()=>{await loadFeature('voice').catch(()=>{});startVoice(text=>{const input=document.querySelector<HTMLInputElement>('#commandInput');if(input){input.value=text;void executeCommand()}},active=>document.querySelector('#voiceBtn')?.classList.toggle('listening',active))});document.querySelector('#refreshNews')?.addEventListener('click',()=>void loadNews((document.querySelector<HTMLSelectElement>('#newsGenre')?.value)||'WORLD'));if(active==='home'&&!newsBooted){newsBooted=true;window.setTimeout(()=>void loadNews('WORLD'),650)}setupMedia()}
async function executeCommand(){const input=document.querySelector<HTMLInputElement>('#commandInput');const reply=document.querySelector('#jarvisReply');if(!input||!reply)return;const text=input.value.trim();if(!text)return;if(/\b(note|notes|remember|remind me|make (?:me )?a note)\b/i.test(text))await loadFeature('notes').catch(()=>{});const result=runCommand(text,telemetry);reply.textContent=result.reply;reply.classList.add('visible');await speakJarvis(result.reply);if(result.value&&['web','media','maps','api','remote','calculator','snake','settings','files','notes'].includes(result.value)){active=result.value as AppId;render()}}
function videoId(raw:string){try{const u=new URL(raw);const h=u.hostname.replace(/^www\./,'').toLowerCase();if(h==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||null;if(h==='youtube.com'||h==='m.youtube.com'){if(u.pathname==='/watch')return u.searchParams.get('v');const p=u.pathname.split('/').filter(Boolean);if(['shorts','live','embed'].includes(p[0]))return p[1]||null}}catch{}return /^[A-Za-z0-9_-]{11}$/.test(raw.trim())?raw.trim():null}
function setupMedia(){const input=document.querySelector<HTMLInputElement>('#videoQuery');const button=document.querySelector('#videoSearch');if(!input||!button)return;button.addEventListener('click',()=>{const id=videoId(input.value.trim());const p=document.querySelector<HTMLElement>('#jarvisPlayer');if(id&&p){p.innerHTML=`<iframe title="JARVIS YouTube player" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?controls=1&playsinline=1&rel=0"></iframe>`;document.querySelector('#mediaState')!.textContent='DIRECT YOUTUBE'}else{document.querySelector('#mediaState')!.textContent='LIVE SEARCH';window.dispatchEvent(new CustomEvent('jarvis:media-search',{detail:{query:input.value.trim()}}))}})}
function renderNews(items:Array<{title?:string;link?:string;source?:string;date?:string}>){const cards=document.querySelector('#newsCards');if(!cards)return;cards.innerHTML=items.slice(0,5).map((a,i)=>`<a class="news-dense-item" href="${esc(a.link||'#')}" target="_blank" rel="noreferrer"><span class="news-rank">${String(i+1).padStart(2,'0')}</span><span class="news-copy"><strong class="news-title">${esc(a.title||'Untitled')}</strong><span class="news-meta"><span class="news-source">${esc(a.source||'LIVE NEWS')}</span>${a.date?`<span class="news-country">${esc(a.date)}</span>`:''}</span></span><span class="news-open">OPEN</span></a>`).join('')||'<div class="news-empty">No live news returned.</div>'}
function newsEndpoint(){const raw=document.querySelector('meta[name="jarvis-intelligence-endpoint"]')?.getAttribute('content')||'https://jarvis-intelligence.shivashisvicky112.workers.dev/api/openai-intelligence';return raw.replace(/\/api\/[^/]+\/?$/,'')+'/api/search'}
async function fetchNewsQuery(query:string,controller:AbortController){const endpoint=`${newsEndpoint()}?q=${encodeURIComponent(query)}`;const response=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok||!Array.isArray(data?.results)||!data.results.length)throw new Error(data?.error||`news HTTP ${response.status}`);return data}
async function loadNews(category:string){const status=document.querySelector('#newsStatus');const cards=document.querySelector('#newsCards');if(!status||!cards)return;const key=category||'WORLD';const cached=newsCache.get(key);if(cached){cards.innerHTML=cached;status.textContent='CACHED';return}newsAbort?.abort();const controller=new AbortController();newsAbort=controller;status.textContent='SCANNING';cards.innerHTML='<div class="news-empty">Fetching headlines…</div>';const queries=key==='INDIA'?['India OR Indian']:key==='AI'?['artificial intelligence OR AI']:key==='TECH'?['technology OR software']:['geopolitics OR international OR global','international relations OR world news'];try{let data:any=null;for(const query of queries){try{data=await fetchNewsQuery(query,controller);break}catch(error){if(controller.signal.aborted)return}}if(!data)throw new Error('No world news provider returned results');const items=data.results.slice(0,5).map((item:{title?:string;link?:string;source?:string;published?:string})=>({title:item.title,link:item.link,source:item.source||data.provider||'LIVE NEWS',date:item.published?new Date(item.published).toLocaleDateString(undefined,{month:'short',day:'numeric'}):''}));renderNews(items);newsCache.set(key,cards.innerHTML);status.textContent=`${items.length} RESULTS`}catch(error){if(controller.signal.aborted)return;status.textContent='DEGRADED';cards.innerHTML='<div class="news-empty">Live news is temporarily unavailable. Try REFRESH.</div>';console.warn('JARVIS news load failed',error)}}
async function bootstrap(){telemetry=await getTelemetry();render()}
void bootstrap();